version: '3.8'
services:
  drake-opensuse:
    build: .
    image: drake-opensuse:latest
    container_name: drake_opensuse_integration
    volumes:
      - ./drake:/drake # Assumes your Drake project is in the './drake' directory
    stdin_open: true # Keeps the container running and allows interactive sessions
    tty: true # Allocates a pseudo-TTY, making it possible to interact with the container

