version: '3.8'
services:
  # drake-opensuse-base:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.base
  #   image: drake-opensuse-base:latest
  #   container_name: drake_opensuse_integration_base
  #   stdin_open: true
  #   tty: true
  drake-opensuse:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #image: drake-opensuse-integration-fmt-10.0.0-spdlog-1.12-built:latest
    #image: drake-opensuse-integration-fmt-10.0.0-spdlog-1.12.0-drake-build:latest
    image: drake-opensuse-integration-fmt-8.1.1-spdlog-1.10-built-fpie-long-drake-build:latest
    container_name: drake_opensuse_integration
    volumes:
      - /home/dan/Projects/Drake-OpenSUSE-Integration/drake:/home/dan/drake # Map the Drake project directory to 'dan's home directory in the container
      - /home/dan/Projects/Drake-OpenSUSE-Integration/clang14.0.0.-build:/home/dan/clang14.0.0.-build # Map the Drake project directory to 'dan's home directory in the container
    stdin_open: true
    tty: true